{"name": "test_invalid_geocode", "status": "failed", "statusDetails": {"message": "AssertionError: assert 200 in [400]\n +  where 200 = <Response [200]>.status_code", "trace": "api_keys = {'api_key1': '1d838399-19c4-4e18-92f9-b9208cc5b4ce', 'api_key2': '954c791f-8d50-4cfc-8827-7eeae0a2d36c'}\nbase_urls = {'geocode_maps': 'https://geocode-maps.yandex.ru/1.x/', 'search_maps': 'https://search-maps.yandex.ru/v1/'}\n\n    def test_invalid_geocode(api_keys, base_urls):\n        url = base_urls[\"geocode_maps\"]\n        params = {\n            \"apikey\": api_keys[\"api_key1\"],\n            \"geocode\": \"!@@@#@$@!&format=json\",\n            \"format\": \"json\"\n        }\n        response = requests.get(url, params=params)\n>       assert response.status_code in [400 or 404]\nE       assert 200 in [400]\nE        +  where 200 = <Response [200]>.status_code\n\nmain.py:79: AssertionError"}, "start": 1725009082262, "stop": 1725009082606, "uuid": "24608084-6645-4d3b-8e3e-57ac6ee08deb", "historyId": "3e18a1b2f1b6272615e2394d9e8d4130", "testCaseId": "3e18a1b2f1b6272615e2394d9e8d4130", "fullName": "main#test_invalid_geocode", "labels": [{"name": "suite", "value": "main"}, {"name": "host", "value": "LAPTOP-NLEPQTU8"}, {"name": "thread", "value": "13296-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "main"}]}